linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forcetypeassert
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecknoinits
  - gocritic
  - godot
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - ireturn
  - loggercheck
  - makezero
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - revive
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagliatelle
  - tenv
  - testableexamples
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - whitespace
  disable:
  - cyclop
  - depguard
  - exhaustruct
  - forbidigo
  - funlen
  - gochecknoglobals
  - gocognit
  - goconst
  - gocyclo
  - godox
  - goerr113
  - gomnd
  - lll
  - maintidx
  - maligned
  - nestif
  - nlreturn
  - paralleltest
  - testpackage
  - varnamelen
  - wrapcheck
  - wsl