name: main
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: '1.22'
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: '1.22'
    - uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
      with:
        version: v1.56.2
