name: main
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
    - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8
      with:
        version: v1.61.0
